#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  HTMotor)
#pragma config(Servo,  srvo_S1_C3_6,    cServo,               tServoContinuousRotation)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "joystickdriver.c"

task main()
{
while(true) {
	PlaySound(soundDownwardTones);
	PlaySound(soundUpwardTones);

		//if (joy1Btn(2)) {
		//	servo[cServo] = 256;
		//	wait1Msec(200);
		//	servo[cServo] = 127;
		//}
		//if (joy1Btn(3)) {
		//	servo[cServo] = 0;
		//	wait1Msec(200);
		//	servo[cServo] = 127;
		//}
	}
}
