#pragma config(Sensor, S3,     IR1,                 sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  motorA,          motorAutoScore, tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#include "Drivers\hitechnic-irseeker-v2.h"
#include "joystickdriver.c"

task main()
{
	int IR1value = SensorValue[IR1];
	while(true)
	{
		eraseDisplay(); //Gets rid of the default joystickdriver status screen
		nxtDisplayCenteredTextLine(5,"%d",IR1value);

		if (joy1Btn(1)) {
			motor[motorAutoScore] = 70;
		}
		if (joy1Btn(2)) {
			motor[motorAutoScore] = -70;
		}
		wait1Msec(3);
	}
}
