#pragma config(Sensor, S3,     IR1,                 sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  motorA,          motorAutoScore, tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#include "Drivers\hitechnic-irseeker-v2.h"
#include "joystickdriver.c"

task main()
{
	while(true)
	{

		if (joy1Btn(1) == 1) {
			motor[motorAutoScore] = 40;
		} else
		if (joy1Btn(2) == 1) {
			motor[motorAutoScore] = -40;
		} else
		{
			motor[motorAutoScore] = 0;
		}
		wait1Msec(3);
	}
}
