#pragma config(Sensor, S3,     IR1,            sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S4,     US1,            sensorSONAR)
#pragma config(Motor,  motorA,          motorAutoScore, tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "Drivers\hitechnic-irseeker-v2.h"
#include "drivers\lego-ultrasound.h"
//#include "joystickdriver.c"

//int dist;
int usvaldist;

task main()
{
	while(true)
	{

		eraseDisplay();
		//dist = USreadDist(US1);
		usvaldist = SensorValue[US1];

		//nxtDisplayTextLine(3, "Dist:  %3d cm", dist);
		nxtDisplayTextLine(3, "SV: %3d cm", usvaldist);
    wait10Msec(50);

	}
}
