#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  none)
#pragma config(Motor,  motorA,          ,              tmotorNormal, openLoop, encoder)
#pragma config(Motor,  motorB,          ,              tmotorNormal, openLoop)
#pragma config(Motor,  motorC,          ,              tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     motorBack1,    tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorBack2,    tmotorNormal, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     motorFront1,   tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorFront2,   tmotorNormal, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_1,     motorLock,     tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motorArm,        tmotorNormal, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//####################################################################################//
//																																										//
//                                2014-2015 3983 TeleOp Code													//
//                         Teams 3983 and 7005 - Highlands Robotics										//
//                                    Code by T. Kluge																//
//																																										//
//####################################################################################//

// User Config ---------------
bool inDebug = true;
// End Config ----------------

#include "JoystickDriver.c"
//#include "../GlobalFunctions/debug.h"

bool canSloMo = true, sloMo = false, revDir = true, canRevDir = true;
bool canLower = true, loweredHalf = false, loweredFull = false, lowered = false;
int srvoVal[] = {103,194};
int ff[] = {490, 613, 640, 750, 640, 750};

task main() {
	nVolume = 3;
	PlayImmediateTone(400, 20);
	waitForStart();
	ClearSounds();
			PlayImmediateTone(ff[0], 10);
			// PlayImmediateTone(ff[1], 10);
			// PlayImmediateTone(ff[2], 10);
			// PlayImmediateTone(ff[3], 20);
			// PlayImmediateTone(ff[4], 10);
			// PlayImmediateTone(ff[5], 40);
	while(true) {

		bFloatDuringInactiveMotorPWM = false;
		getJoystickSettings(joystick);

		if((joystick.joy1_y1 < 10 && joystick.joy1_y1 > -10) && (joystick.joy1_x1 < 10 && joystick.joy1_x1 > -10))
		{
			joystick.joy1_y1 = 0;
			joystick.joy1_x1 = 0;
		}
		if((joystick.joy1_x2 < 10 && joystick.joy1_x2 > -10) && (joystick.joy1_y2 < 10 && joystick.joy1_y2 > -10))
		{
			joystick.joy1_x2 = 0;
			joystick.joy1_y2 = 0;
		}
		if((joystick.joy2_y1 < 10 && joystick.joy2_y1 > -10) && (joystick.joy2_x1 < 10 && joystick.joy2_x1 > -10))
		{
			joystick.joy2_y1 = 0;
			joystick.joy2_x1 = 0;
		}
		if((joystick.joy2_x2 < 10 && joystick.joy2_x2 > -10) && (joystick.joy2_y2 < 10 && joystick.joy2_y2 > -10))
		{
			joystick.joy2_x2 = 0;
			joystick.joy2_y2 = 0;
		}

		if (!revDir) {
			if (!sloMo) {
				motor[motorBack1] = (joystick.joy1_y1 - joystick.joy1_x2);
				motor[motorFront1] = (joystick.joy1_y1 - joystick.joy1_x2);
				motor[motorBack2] = (joystick.joy1_y1 + joystick.joy1_x2);
				motor[motorFront2] = (joystick.joy1_y1 + joystick.joy1_x2);
			} else {
				motor[motorBack1] = 0.16 * (joystick.joy1_y1 - joystick.joy1_x2);
				motor[motorFront1] = 0.16 * (joystick.joy1_y1 - joystick.joy1_x2);
				motor[motorBack2] = 0.16 * (joystick.joy1_y1 + joystick.joy1_x2);
				motor[motorFront2] = 0.16 * (joystick.joy1_y1 + joystick.joy1_x2);
			}
		} else {
			if (!sloMo) {
				motor[motorBack1] = -(joystick.joy1_y1 + joystick.joy1_x2);
				motor[motorFront1] = -(joystick.joy1_y1 + joystick.joy1_x2);
				motor[motorBack2] = -(joystick.joy1_y1 - joystick.joy1_x2);
				motor[motorFront2] = -(joystick.joy1_y1 - joystick.joy1_x2);
			} else {
				motor[motorBack1] = -0.16 * (joystick.joy1_y1 + joystick.joy1_x2);
				motor[motorFront1] = -0.16 * (joystick.joy1_y1 + joystick.joy1_x2);
				motor[motorBack2] = -0.16 * (joystick.joy1_y1 - joystick.joy1_x2);
				motor[motorFront2] = -0.16 * (joystick.joy1_y1 - joystick.joy1_x2);
			}
		}
		if (canSloMo) {
			if (!sloMo) {
				if (joy1Btn(12)) {
					sloMo = true;
					canSloMo = false;
					PlayImmediateTone(400, 10);
				}
			} else {
				if (joy1Btn(12)) {
					sloMo = false;
					canSloMo = false;
					PlayImmediateTone(600, 10);
				}
			}
		}
		if (!canSloMo) {
			if (!joy1Btn(12)) {
				canSloMo = true;
			}
		}
		if (canRevDir) {
			if (!revDir) {
				if (joy1Btn(11)) {
					revDir = true;
					canRevDir = false;
					PlayImmediateTone(300, 10);
				}
			} else {
				if (joy1Btn(11)) {
					revDir = false;
					canRevDir = false;
					PlayImmediateTone(800, 10);
				}
			}
		}
		if (!canRevDir) {
			if (!joy1Btn(11)) {
				canRevDir = true;
			}
		}

		// -------------------------------	End Drive Code	-------------------------------

		// if (canLower) {
		  // if (!lowered) { //if not lowered
		    // if (joy1Btn(1) || joy2Btn(1) && !loweredFull) {
		      // motor[motorLock] = -50;
		      // wait1Msec(105);
		      // motor[motorLock] = 0;
		      // lowered = true;
		      // loweredHalf = true;
		      // canLower = false;
		    // }
		    // if (joy1Btn(2) || joy2Btn(2) && !loweredHalf) {
		      // motor[motorLock] = -50;
		      // wait1Msec(200);
		      // motor[motorLock] = 0;
		      // lowered = true;
		      // loweredFull = true;
		      // canLower = false;
		    // }
		  // } else { //if lowered
		    // if (joy1Btn(1) || joy2Btn(1) && !loweredHalf) {
		      // motor[motorLock] = 50;
		      // wait1Msec(105);
		      // motor[motorLock] = 0;
		      // lowered = false;
		      // loweredHalf = false;
		      // loweredFull = false;
		      // canLower = false;
		    // }
		    // if (joy1Btn(2) || joy2Btn(2) && !loweredFull) {
		      // motor[motorLock] = 50;
		      // wait1Msec(200);
		      // motor[motorLock] = 0;
		      // lowered = false;
		      // loweredFull = false;
		      // loweredHalf = false;
		      // canLower = false;
		    // }
		  // }
		// } else {
		  // if (!joy1Btn(1) && !joy2Btn(1)) {
		    // canLower = true;
		  // }
		// }
		if (joy2Btn(6)) {
		  motor[motorLock] = 30;
		} else if (joy2Btn(8)) {
		  motor[motorLock] = -30;
		} else {
		  motor[motorLock]= 0;
		}
		if (joy2Btn(12))
		  motor[motorArm] = joystick.joy2_x2 / 7;
		else
		  motor[motorArm] = 0;
	}
}
