#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S2,     sensorLight,    sensorLightActive)
#pragma config(Motor,  mtr_S1_C1_1,     motorLeft,     tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     motorRight,    tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     motorLift,     tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     motorScoop,    tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     motorH,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motorI,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C4_1,    servo1,               tServoStandard)
#pragma config(Servo,  srvo_S1_C4_2,    servo2,               tServoStandard)
#pragma config(Servo,  srvo_S1_C4_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

			//####################################################################################//
			//																																										//
			//															  2013-2014 TeleOp Code					  										//
			//													  Team 3983 - Highlands Robotics													//
			//																   Code by T. Kluge																	//
			//																																										//
			//####################################################################################//

//referenced files here

#include "joystickdriver.c"

//vars + functions here
int speedScoop = 70;

task main()
{
	waitForStart();

	while(true) {

	bFloatDuringInactiveMotorPWM = false;
	getJoystickSettings(joystick);
	//Anti-RageQuit code (prevents movement when the joysticks are just a bit off)

		if((joystick.joy1_y1<10&&joystick.joy1_y1>-10)&&(joystick.joy1_x1<10&&joystick.joy1_x1>-10))
		{
			joystick.joy1_y1=0;
			joystick.joy1_x1=0;
		}
		if((joystick.joy1_x2<10&&joystick.joy1_x2>-10)&&(joystick.joy1_y2<10&&joystick.joy1_y2>-10))
		{
			joystick.joy1_x2=0;
			joystick.joy1_y2=0;
		}

		//main drive motor control

		motor[motorLeft] = (joystick.joy1_y1 + joystick.joy1_x2);
		motor[motorRight] = (joystick.joy1_y1 - joystick.joy1_x2);

		//main arm up/down control
		if (joystick.joy1_TopHat == 0) {
			motor[motorScoop] = speedScoop;
		} else {
			if (joystick.joy1_TopHat == 4) {
				motor[motorScoop] = -speedScoop;
			} else {
				motor[motorScoop] = 0;
			}
		}

		if (joy1Btn(4)) {
			speedScoop++;
			PlayTone((speedScoop + 400), 10);
		}
		if (joy1Btn(2)) {
			speedScoop--;
			PlayTone((speedScoop + 400), 10);
		}

		//hipposcoop
		if (joy1Btn(12)) {
			motor[motorLift] = 100;
		} else {
			motor[motorLift] = 0;
		}

		//main arm bucket control
		if (joy2Btn(4)) {
			servo[srvo_S1_C4_1] = 0;
		} else if (joy2Btn(2)) {
			servo[srvo_S1_C4_1] = 120;
		}

		if (bDisconnected) {
			joystick.joy1_y1 = 0;
			joystick.joy1_y2 = 0;
			joystick.joy2_TopHat = -1;
		}

		//Anti-jitter
		wait1Msec(10);
	}//end of main while(true)
}//end of task(main)
