#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S1,     HTIRS2L,        sensorNone)
#pragma config(Sensor, S3,     HTSMUX,         sensorNone)
#pragma config(Sensor, S4,     US1,            sensorNone)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop, encoder)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorTetrix, PIDControl)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, PIDControl, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     motorF,        tmotorTetrix, PIDControl)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorTetrix, PIDControl)
#pragma config(Motor,  mtr_S1_C3_1,     motorH,        tmotorTetrix, PIDControl)
#pragma config(Motor,  mtr_S1_C3_2,     motorI,        tmotorTetrix, PIDControl)
#pragma config(Servo,  srvo_S1_C4_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//####################################################################################//
//
//                                   2014-2015 TeleOp Code
//                               Team 3983 - Highlands Robotics
//                                      Code by T. Kluge
//
//####################################################################################//


#include "JoystickDriver.c"

bool reversedControl = false;
bool canSwitchDriveSpeed = true;

task main() {
	waitForStart();
	while(true) {

			bFloatDuringInactiveMotorPWM = false;
			getJoystickSettings(joystick);

			//CONTROLLER 1 JOYSTICK 1 - Drive (Forward/Backward)
			if((joystick.joy1_y1 < 10 && joystick.joy1_y1 > -10) && (joystick.joy1_x1 < 10 && joystick.joy1_x1 > -10))
			{
				joystick.joy1_y1 = 0;
				joystick.joy1_x1 = 0;
			}
			//CONTROLLER 1 JOYSTICK 2 - Drive (Turning)
			if((joystick.joy1_x2 < 10 && joystick.joy1_x2 > -10) && (joystick.joy1_y2 < 10 && joystick.joy1_y2 > -10))
			{
				joystick.joy1_x2 = 0;
				joystick.joy1_y2 = 0;
			}

			if (!reversedControl) {
				motor[motorLeft] = (joystick.joy1_y1 + joystick.joy1_x2);
				motor[motorRight] = (joystick.joy1_y1 - joystick.joy1_x2);
			} else {
			motor[motorLeft] = -(joystick.joy1_y1 - joystick.joy1_x2);
				motor[motorRight] = -(joystick.joy1_y1 + joystick.joy1_x2);
			}
			if (canSwitchDriveSpeed) {
				if (!reversedControl) {
					if (joy1Btn(1) == 1) {
						reversedControl = true;
						canSwitchDriveSpeed = false;
					}
				} else {
					if (joy1Btn(1) == 1) {
						reversedControl = false;
						canSwitchDriveSpeed = false;
					}
				}
			} else {
				if (joy1Btn(1) == 0) {
					canSwitchDriveSpeed = true; //wait until button is released to let switch again
				}
			}
			

		} //while true
	} //task main
