#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  HTMotor)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     sensorLight,    sensorNone)
#pragma config(Motor,  mtr_S1_C1_1,     motorLeft,     tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     motorRight,    tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     motorLift,     tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     motorScoop,    tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C4_1,     motorSpin,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     motorI,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    servo1,               tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//####################################################################################//
//																																										//
//															  2013-2014 TeleOp Code					  										//
//													  Team 3983 - Highlands Robotics													//
//																   Code by T. Kluge																	//
//																																										//
//####################################################################################//


#include "joystickdriver.c"
//vars + functions here
int speedScoop = 50;
int servoGo = 0;
bool tucked = true;

void killall() {
	motor[motorLeft] = 0;
	motor[motorRight] = 0;
	motor[motorLift] = 0;
	motor[motorScoop] = 0;
	PlaySound(soundException);
	PlaySound(soundDownwardTones);
}

task main()
{
	PlaySound(soundFastUpwardTones);
	waitForStart();
	PlaySound(soundBeepBeep);

	while(true) {

		bFloatDuringInactiveMotorPWM = false;
		getJoystickSettings(joystick);
		//Anti-RageQuit code (prevents movement when the joysticks are just a bit off)

		if((joystick.joy1_y1<10&&joystick.joy1_y1>-10)&&(joystick.joy1_x1<10&&joystick.joy1_x1>-10))
		{
			joystick.joy1_y1=0;
			joystick.joy1_x1=0;
		}
		if((joystick.joy1_x2<10&&joystick.joy1_x2>-10)&&(joystick.joy1_y2<10&&joystick.joy1_y2>-10))
		{
			joystick.joy1_x2=0;
			joystick.joy1_y2=0;
		}

		//main drive motor control

		motor[motorLeft] = (joystick.joy1_y1 + joystick.joy1_x2);
		motor[motorRight] = (joystick.joy1_y1 - joystick.joy1_x2);

		//main arm up/down control
		if (joystick.joy2_TopHat == 4 || joy1Btn(5)) {
			motor[motorScoop] = 15;
			} else {
			if (joystick.joy2_TopHat == 0 || joy1Btn(6)) {
				motor[motorScoop] = -15;
				} else {
				motor[motorScoop] = 0;
			}
		}
		/*
		if (joy1Btn(4)) {
		speedScoop++;
		PlayTone((speedScoop + 400), 10);
		}
		if (joy1Btn(2)) {
		speedScoop--;
		PlayTone((speedScoop + 400), 10);
		}
		*/

		//hipposcoop
		if (joy2Btn(12)) {
			alive();
			motor[motorLift] = 100;
			} else {
			motor[motorLift] = 0;
		}

		//main arm bucket clamp control
		if (joy2Btn(1)) {
			servo[servo1] = 165;
			} else if (joy2Btn(3)) {
			servo[servo1] = 0;
		}

		if (joy2Btn(11) || joy1Btn(11)) {
		//Flag servo tuck-in control
		if (joy2Btn(4)) {
			servo[srvo_S1_C3_2] = 255;
			servoGo = 0;
			tucked = true;
		}
		if (joy2Btn(2)) {
			servo[srvo_S1_C3_2] = 132;
			servoGo = 1;
			tucked = false;
		}

		//Flag Motor Control
		//if (servoGo == 1) {
			if (joy2Btn(5)) {
				motor[motorSpin] = 100;
				} else if (joy2Btn(6)) {
				motor[motorSpin] = -100;
				} else {
				motor[motorSpin] = 0;
			}
		}
		//}

		//main arm control
		if (joy2Btn(7)) {
			motor[mtr_S1_C2_1] = 25;
			} else if (joy2Btn(8)) {
			motor[mtr_S1_C2_1] = -25;
			//} else if (joy2Btn(5)) {
			//motor[mtr_S1_C2_1] = 15;
			//} else if (joy2Btn(6)) {
			//motor[mtr_S1_C2_1] = -15;
			} else {
			motor[mtr_S1_C2_1] = 0;
		}

		if (joy1Btn(11) && joy1Btn(12)) {
			killall();
		}
		if (joy2Btn(11) && joy2Btn(12)) {
			killall();
		}

		if (bDisconnected) {
			joystick.joy1_y1 = 0;
			joystick.joy1_y2 = 0;
			joystick.joy2_TopHat = -1;
		}

		//Anti-jitter
		wait1Msec(10);
	}//end of main while(true)
}//end of task(main)
