#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  HTMotor)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     sensorLight,    sensorLightActive)
#pragma config(Motor,  motorA,          motorAutoScore, tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     motorLeft,     tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     motorRight,    tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     motorArm,      tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     motorScoop,    tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C4_1,     motorLift,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     motorI,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    servoSweep,           tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    servoLift,            tServoStandard)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//####################################################################################//
//
//                                   2013-2014 TeleOp Code
//                               Team 3983 - Highlands Robotics
//                                      Code by T. Kluge
//
//####################################################################################//


#include "JoystickDriver.c"

void scoreCube();

task main()

{
	waitForStart();

	while(true) {

		bFloatDuringInactiveMotorPWM = false;
		getJoystickSettings(joystick);
		//Anti-RageQuit code (prevents movement when the joysticks are just a bit off)

		//CONTROLLER 1 JOYSTICK 1 - Drive (Forward/Backward)
		if((joystick.joy1_y1<10&&joystick.joy1_y1>-10)&&(joystick.joy1_x1<10&&joystick.joy1_x1>-10))
		{
			joystick.joy1_y1=0;
			joystick.joy1_x1=0;
		}
		//CONTROLLER 1 JOYSTICK 2 - Drive (Turning)
		if((joystick.joy1_x2<10&&joystick.joy1_x2>-10)&&(joystick.joy1_y2<10&&joystick.joy1_y2>-10))
		{
			joystick.joy1_x2=0;
			joystick.joy1_y2=0;
		}
		//CONTROLLER 2 JOYSTICK 2 - Flag lift motor
		if(joystick.joy2_x2<10&&joystick.joy2_x2>-10)
		{
			joystick.joy2_x2=0;
		}

		//main drive motor control

		motor[motorLeft] = (joystick.joy1_y1 + joystick.joy1_x2);
		motor[motorRight] = (joystick.joy1_y1 - joystick.joy1_x2);

		//SWEEPER ARM
		if (joystick.joy2_TopHat == 0 || joy1Btn(7)) { //Joy2TopHat or Joy1 lBumber
			motor[motorScoop] = 100;
			} else if (joystick.joy2_TopHat == 4 || joy1Btn(8)) { //Joy2TopHat or Joy1 rBumper
			motor[motorScoop] = -100;
			} else {
			motor[motorScoop] = 0;
		}


		//WORM GEAR ARM DRIVE
		if (ServoValue[servoSweep] < 125) { //makes sure the sweeper arm is lifted up before the main arm can move
			if (joy2Btn(5)) {									//so that the main arm cannot get stuck on the sweeper arm.
				servo[servoSweep] = 0;//sets the sweeper arm to upward pos just in case
				motor[motorArm] = 100;
				} else if(joy2Btn(6)) {
				servo[servoSweep] = 0;//sets the sweeper arm to upward pos just in case
				motor[motorArm] = -100;
				} else {
				motor[motorArm] = 0;
			}
		}

		/*
		//BUCKET CLAMP
		if (joy2Btn(7)) { //Left Trigger
			servo[servoClamp] = 25;
			} else if (joy2Btn(8)) { //Right Trigger
			servo[servoClamp] = 157;
		}
*/

		//SWEEPER ARM RAISE/LOWER
		if (joy2Btn(3) || joy1Btn(6)) { //Joy2 bPadRight or Joy1 rBumper
			servo[servoSweep] = 0;//Raised
			motor[motorScoop] = -100;//sets the bevel gears in by spinning sweeper motor
			wait1Msec(300);
			motor[motorScoop] = 0;
			} else if (joy2Btn(1) || joy1Btn(5)) { //Joy2 bPadLeft or Joy1 lBumper
			servo[servoSweep] = 130;//Lowered
		}

		//SECTION FOR FLAG LIFTER
		if (joy2Btn(2)) { //bPadTop
			servo[servoLift] = 124;
			} else if (joy2Btn(4)) {//bPadBottom
			servo[servoLift] = 225;
			motor[motorLift] = 0;
		}
		motor[motorLift] = joystick.joy2_x2;

		//TEST THING
		if (bDisconnected) {
			joystick.joy1_y1 = 0;
			joystick.joy1_y2 = 0;
			joystick.joy2_TopHat = -1;
		}

		if (joy2Btn(11)) {
			scoreCube();
		}
		//Anti-jitter
		wait1Msec(10);
	}//end of main while(true)
}//end of task(main)

void scoreCube() {
	motor[motorAutoScore] = 40;
	wait1Msec(500);
	motor[motorAutoScore] = 0;

	motor[motorAutoScore] = -40;
	wait1Msec(500);
	motor[motorAutoScore] = 0;
}
