#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  HTMotor)
#pragma config(Hubs,  S2, HTMotor,  none,     none,     none)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop, encoder)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     motorFront1,   tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     motorFront2,   tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motorBack1,    tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     motorBack2,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     motorLock,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     motorBelt,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S2_C1_1,     motorLift,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_2,     motorLift2,    tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    servoTilt,            tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    servoDoor,            tServoStandard)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servoTest,            tServoContinuousRotation)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//####################################################################################//
//																																										//
//                                2014-2015 Autonomous Code														//
//                         Teams 3983 and 7005 - Highlands Robotics										//
//                                    Code by T. Kluge																//
//																																										//
//####################################################################################//

// User Config ---------------
bool inDebug = true;
// End Config ----------------

#include "../drivers/JoystickDriver_CustomNoSplash.c"

//variable initialization

//Main Program

task main() {
	waitForStart();

	motor[motorFront1] = 100;
	motor[motorFront2] = 100;
	motor[motorBack1] = 100;
	motor[motorBack2] = 100;
	wait1Msec(3000);
	motor[motorFront1] = -100;
	motor[motorFront2] = 100;
	motor[motorBack1] = -100;
	motor[motorBack2] = 100;
	wait1Msec(1000);
	motor[motorFront1] = 100;
	motor[motorFront2] = 100;
	motor[motorBack1] = 100;
	motor[motorBack2] = 100;
	wait1Msec(2000);
	motor[motorFront1] = 0;
	motor[motorFront2] = 0;
	motor[motorBack1] = 0;
	motor[motorBack2] = 0;



} //end task main
