#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     Sonar,          sensorSONAR)
#pragma config(Sensor, S3,     Ir,             sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  mtr_S1_C1_1,     motorLeft,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorRight,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motorBelt,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorLift,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     motorSweeper,  tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motorUndef,    tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C4_1,    servoClamp,           tServoNone)
#pragma config(Servo,  srvo_S1_C4_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "joystickdriver.c"

int bucketOpenVal = 110;
int bucketCloseVal = 12;
void stopAllMotors();

task main()
{
	PlaySound(soundBeepBeep);
	waitForStart();
	PlaySound(soundUpwardTones);

	while (true) {
		motor[motorLeft] = 100;
		motor[motorRight] = 100;

		if(SensorValue[Sonar] <= 5){ //dist > 5
			motor[motorLift] = 100;
			wait1Msec(2000);
			stopAllMotors();
			motor[motorLift] = 0;
		} else if(SensorValue[Sonar] > 5) { //dist <= 5
			motor[motorLift] = 0;
		}

		wait1Msec(100); //anti-jitter
	}

}

void stopAllMotors() {
	motor[0] = 0;
	motor[1] = 0;
}


/* changes by ali for the IR sensor
added an Ir sensor (Ir)*/

	if(SensorValue[Ir] <= 4)
	{
		motor[motorLeft]=-50;
		motor[motorRight]=50;
		wait1Msec(2000);
		nxtDisplayString("hello");


		motor[motorLeft]= 100;
		motor[motorRight]= 100;
		wait1Msec(10000);
		nxtDisplayString("hola");
	}
