#pragma config(Hubs,  S3, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S3,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S3_C1_1,     motorLift,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S3_C1_2,     motorLift,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S3_C2_1,     motorRight,    tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S3_C2_2,     motorUndef1,   tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S3_C3_1,     motorSweep,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S3_C3_2,     motorLeft,     tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S3_C4_1,    servo1,               tServoStandard)
#pragma config(Servo,  srvo_S3_C4_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S3_C4_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S3_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S3_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S3_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "joystickdriver.c"

task main()
 {
	PlaySound(soundBeepBeep);
	waitForStart();
	PlaySound(soundUpwardTones);
	while(true)
	{

		getJoystickSettings(joystick);
		//Prevents random movement on the y axis
		if(joystick.joy1_y1 < 10 && joystick.joy1_y1 > -10) {
			joystick.joy1_y1 = 0;
		}
		//Prevents random movement on the x axis
		if(joystick.joy1_x2 < -10 && joystick.joy1_x2 > 10) {
			joystick.joy1_x2 = 0;
		}

		//Drive Control
		motor[motorLeft] = (joystick.joy1_y1);
		motor[motorRight] = (joystick.joy1_y2);

		//Main Arm Control

			//motor[mtr_S3_C2_1] = (joystick.joy2_y1) / 1.5;
			//motor[mtr_S3_C2_2] = (joystick.joy2_y2) / 4;



		if(joystick.joy1_TopHat == 2 || joy2Btn(6)) {
			motor[motorSweep] = 70;
			} else if (joystick.joy1_TopHat == 6 || joy2Btn(5)) {
			motor[motorSweep] = -70;
			} else {
			motor[motorSweep] = 0;
		}

		if (joy2Btn(2)) {
				motor[motorLift] = 100;
				} else if (joy2Btn(3)) {
				motor[motorLift] = -100;
				} else {
				motor[motorLift] = 0;
			}

	}//end of while loop
}//end of task
