#pragma config(Hubs,  S1, HTMotor,  HTMotor,   HTMotor,  HTServo)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop, encoder)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     motorLeft,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorRight,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motorBelt,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorLift,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     motorH,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motorI,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C4_1,    servoLeft,            tServoNone)
#pragma config(Servo,  srvo_S1_C4_2,    servoRight,           tServoNone)
#pragma config(Servo,  srvo_S1_C4_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//####################################################################################//
//																																										//
//                                 2014-2015 TeleOp Code															//
//                         Teams 3983 and 7005 - Highlands Robotics										//
//                                    Code by T. Kluge																//
//																																										//
//####################################################################################//

// User Config ---------------
bool inDebug = true;
// End Config ----------------

#include "JoystickDriver.c"
#include "../GlobalFunctions/debug.h"

bool reversedControl = false;
bool canSwitchDriveSpeed = true;

int servoVal_left_up = 135,
		servoVal_left_down = 0;
int servoVal_right_up = 109,
		servoVal_right_down = 240;

task main() {

//Initialize servos
servo[srvo_S1_C4_1] = servoVal_left_up;
servo[srvo_S1_C4_2] = servoVal_right_up;
//end init
	waitForStart();
	while(true) {

		bFloatDuringInactiveMotorPWM = false;
		getJoystickSettings(joystick);

		//Prevents random movement on the y axis
		if((joystick.joy1_y1 < 10 && joystick.joy1_y1 > -10) && (joystick.joy1_y2 < -10 && joystick.joy1_y2 > 10))
		{
			joystick.joy1_y1 = 0;
			joystick.joy1_y2 = 0;
		}
		//Prevents random movement on the x axis
		if((joystick.joy1_x2 < -10 && joystick.joy1_x2 > 10) && (joystick.joy1_x1 < 10 && joystick.joy1_x1 > -10))
		{
			joystick.joy1_x2 = 0;
			joystick.joy1_x1 = 0;
		}

		//Drive Control
		if (!reversedControl) {
			motor[motorLeft] = (joystick.joy1_y1);
			motor[motorRight] = (joystick.joy1_y2);
		//} else {
		//	motor[motorLeft] = -(joystick.joy1_y1);
		//	motor[motorRight] = -(joystick.joy1_y2);
		}
		// -------------------------------	End Drive Code	-------------------------------
		if (joy2Btn(7)) {
			motor[motorBelt] = -100;
		} else if (joy2Btn(5)) {
			motor[motorBelt] = 100;
		} else {
			motor[motorBelt] = 0;
		}

		if (joy2Btn(2)){
			motor[motorLift] = -100;
		}else if (joy2Btn(3)){
			motor[motorLift] = 100;
		}else{
			motor[motorLift] = 0;
		}

	//	if (joy2Btn(6)) {
	//		//servo[servoLeft] = servoVal_open;
		//	servo[srvo_S1_C4_1] = servoVal_left_up;
			//servo[srvo_S1_C4_2] = servoVal_right_up;
		//}
		//if (joy2Btn(8)) {
		//	servo[srvo_S1_C4_1] = servoVal_left_down;
		//	servo[srvo_S1_C4_2] = servoVal_right_down;
		}
	}
 //task main
