#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  HTMotor)
#pragma config(Hubs,  S2, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop, encoder)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     motorFront1,       tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     motorFront2,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motorBack1,       tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     motorBack2,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     motorLock,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     motorBelt,    tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S2_C1_1,     motorLift,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_2,     motorLift2,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    servoTilt,               tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    servoDoor,               tServoStandard)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servoTest,               tServoContinuousRotation)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//####################################################################################//
//																																										//
//                                2014-2015 7005 TeleOp Code													//
//                         Teams 3983 and 7005 - Highlands Robotics										//
//                                    Code by T. Kluge																//
//																																										//
//####################################################################################//

// User Config ---------------
bool inDebug = true;
bool tankDrive = false;
// End Config ----------------

#include "JoystickDriver.c"
//#include "../GlobalFunctions/debug.h"

bool canSloMo = true, sloMo = false, revDir = false, canRevDir = true;
bool canLower = true, lowered = false;
int srvoVal[][] = {{157,80}, //down, up //clamp
	{154,126}}; //up, down //door
int ff[] = {490, 640, 750, 640, 750};
task main() {
	nVolume = 3;
	//servo[srvoF1] = srvoVal[0][1];
	//servo[servoStop] = srvoVal[1][0];
	PlayImmediateTone(500, 40);
	waitForStart();
	ClearSounds();
	PlayImmediateTone(ff[0], 20);
	// PlayImmediateTone(ff[1], 10);
	// PlayImmediateTone(ff[2], 20);
	// PlayImmediateTone(ff[3], 10);
	// PlayImmediateTone(ff[4], 40);
	while(true) {

		bFloatDuringInactiveMotorPWM = false;
		getJoystickSettings(joystick);

		if((joystick.joy1_y1 < 10 && joystick.joy1_y1 > -10) && (joystick.joy1_x1 < 10 && joystick.joy1_x1 > -10))
		{
			joystick.joy1_y1 = 0;
			joystick.joy1_x1 = 0;
		}
		if((joystick.joy1_x2 < 10 && joystick.joy1_x2 > -10) && (joystick.joy1_y2 < 10 && joystick.joy1_y2 > -10))
		{
			joystick.joy1_x2 = 0;
			joystick.joy1_y2 = 0;
		}

		if (!revDir) {
			if (!sloMo) {
				motor[motorBack1] = (joystick.joy1_y1 + joystick.joy1_x2);
				motor[motorFront1] = (joystick.joy1_y1 + joystick.joy1_x2);
				motor[motorBack2] = (joystick.joy1_y1 - joystick.joy1_x2);
				motor[motorFront2] = (joystick.joy1_y1 - joystick.joy1_x2);
				} else {
				motor[motorBack1] = 0.16 * (joystick.joy1_y1 + joystick.joy1_x2);
				motor[motorFront1] = 0.16 * (joystick.joy1_y1 + joystick.joy1_x2);
				motor[motorBack2] = 0.16 * (joystick.joy1_y1 - joystick.joy1_x2);
				motor[motorFront2] = 0.16 * (joystick.joy1_y1 - joystick.joy1_x2);
			}
		} else {
			if (!sloMo) {
				motor[motorBack1] = -(joystick.joy1_y1 - joystick.joy1_x2);
				motor[motorFront1] = -(joystick.joy1_y1 - joystick.joy1_x2);
				motor[motorBack2] = -(joystick.joy1_y1 + joystick.joy1_x2);
				motor[motorFront2] = -(joystick.joy1_y1 + joystick.joy1_x2);
				} else {
				motor[motorBack1] = -0.16 * (joystick.joy1_y1 - joystick.joy1_x2);
				motor[motorFront1] = -0.16 * (joystick.joy1_y1 - joystick.joy1_x2);
				motor[motorBack2] = -0.16 * (joystick.joy1_y1 + joystick.joy1_x2);
				motor[motorFront2] = -0.16 * (joystick.joy1_y1 + joystick.joy1_x2);
			}
		}
		if (canSloMo) {
			if (!sloMo) {
				if (joy1Btn(12)) {
					sloMo = true;
					canSloMo = false;
					PlayImmediateTone(400, 10);
				}
				} else {
				if (joy1Btn(12)) {
					sloMo = false;
					canSloMo = false;
					PlayImmediateTone(600, 10);
				}
			}
		}
		if (!canSloMo) {
			if (!joy1Btn(12)) {
				canSloMo = true;
			}
		}
		if (canRevDir) {
			if (!revDir) {
				if (joy1Btn(11)) {
					revDir = true;
					canRevDir = false;
					PlayImmediateTone(300, 10);
				}
				} else {
				if (joy1Btn(11)) {
					revDir = false;
					canRevDir = false;
					PlayImmediateTone(800, 10);
				}
			}
		}
		if (!canRevDir) {
			if (!joy1Btn(11)) {
				canRevDir = true;
			}
		}

		// -------------------------------	End Drive Code	-------------------------------
		if (joystick.joy2_TopHat == 0) {
			motor[motorLift] = 100;
			motor[motorLift2] = 100;
			} else if (joystick.joy2_TopHat == 4) {
			motor[motorLift] = -100;
			motor[motorLift2] = -100;
			} else {
			motor[motorLift] = 0;
			motor[motorLift2] = 0;
		}

		if (joy2Btn(1) || joy1Btn(1))
			motor[motorBelt] = 100;
		else if (joy2Btn(4) || joy1Btn(4))
			motor[motorBelt] = -100;
		else
			motor[motorBelt] = 0;


		 if (joy2Btn(2)) {
		 servo[servoDoor] = ServoValue[servoDoor] + 3;
		 }
		 if (joy2Btn(3)) {
		 servo[servoDoor] = ServoValue[servoDoor] - 3;
		 }
		if (joy2Btn(6)) {
			servo[servoTilt] = ServoValue[servoTilt] + 3;
		} else if (joy2Btn(8)) {
			servo[servoTilt] = ServoValue[servoTilt] - 3;
		}
		if (joy2Btn(5)) {
			motor[motorLock] = 30;
			} else if (joy2Btn(7)) {
			motor[motorLock] = -30;
			} else {
			motor[motorLock]= 0;
		}

	} //while true
} //task main
