#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Hubs,  S2, HTServo,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Motor,  motorA,          ,              tmotorNormal, openLoop, encoder)
#pragma config(Motor,  motorB,          ,              tmotorNormal, openLoop)
#pragma config(Motor,  motorC,          ,              tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     motorRight,    tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorLeft,     tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motorLift,     tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorBelt,     tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     motorLock,     tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motorUnused,   tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     motorLift2,    tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     motorLift3,    tmotorNormal, openLoop, reversed)
#pragma config(Servo,  srvo_S2_C1_1,    servoSweep,           tServoStandard)
#pragma config(Servo,  srvo_S2_C1_2,    servoStop,            tServoStandard)
#pragma config(Servo,  srvo_S2_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//####################################################################################//
//																																										//
//                                2014-2015 7005 TeleOp Code													//
//                         Teams 3983 and 7005 - Highlands Robotics										//
//                                    Code by T. Kluge																//
//																																										//
//####################################################################################//

// User Config ---------------
bool inDebug = true;
bool tankDrive = false;
// End Config ----------------

#include "JoystickDriver.c"
//#include "../GlobalFunctions/debug.h"

bool canSloMo = true, sloMo = false, revDir = false, canRevDir = true;
bool canLower = true, lowered = false;
int srvoVal[][] = {{157,80}, //down, up //clamp
									 {154,126}}; //up, down //door
int ff[] = {490, 640, 750, 640, 750};
task main() {
	nVolume = 3;
	//servo[srvoF1] = srvoVal[0][1];
	servo[servoStop] = srvoVal[1][0];
	PlayImmediateTone(500, 40);
	waitForStart();
	ClearSounds();
			PlayImmediateTone(ff[0], 20);
			// PlayImmediateTone(ff[1], 10);
			// PlayImmediateTone(ff[2], 20);
			// PlayImmediateTone(ff[3], 10);
			// PlayImmediateTone(ff[4], 40);
	while(true) {

		bFloatDuringInactiveMotorPWM = false;
		getJoystickSettings(joystick);

		if((joystick.joy1_y1 < 10 && joystick.joy1_y1 > -10) && (joystick.joy1_x1 < 10 && joystick.joy1_x1 > -10))
		{
			joystick.joy1_y1 = 0;
			joystick.joy1_x1 = 0;
		}
		if((joystick.joy1_x2 < 10 && joystick.joy1_x2 > -10) && (joystick.joy1_y2 < 10 && joystick.joy1_y2 > -10))
		{
			joystick.joy1_x2 = 0;
			joystick.joy1_y2 = 0;
		}

		if (!tankDrive) {
		if (!revDir) {
			if (!sloMo) {
				motor[motorLeft] = (joystick.joy1_y1 + joystick.joy1_x2);
				motor[motorRight] = (joystick.joy1_y1 - joystick.joy1_x2);
			} else {
				motor[motorLeft] = 0.16 * (joystick.joy1_y1 + joystick.joy1_x2);
				motor[motorRight] = 0.16 * (joystick.joy1_y1 - joystick.joy1_x2);
			}
		} else {
			if (!sloMo) {
				motor[motorLeft] = -(joystick.joy1_y1 - joystick.joy1_x2);
				motor[motorRight] = -(joystick.joy1_y1 + joystick.joy1_x2);
			} else {
				motor[motorLeft] = -0.16 * (joystick.joy1_y1 - joystick.joy1_x2);
				motor[motorRight] = -0.16 * (joystick.joy1_y1 + joystick.joy1_x2);
			}
		}
  } else {
		if (!sloMo) {
			motor[motorLeft] = (joystick.joy1_y1);
			motor[motorRight] = (joystick.joy1_y2);
		} else {
			motor[motorLeft] = 0.3 * (joystick.joy1_y1);
			motor[motorRight] = 0.3 * (joystick.joy1_y2);
		}
}
		if (canSloMo) {
			if (!sloMo) {
				if (joy1Btn(12)) {
					sloMo = true;
					canSloMo = false;
					PlayImmediateTone(400, 10);
				}
			} else {
				if (joy1Btn(12)) {
					sloMo = false;
					canSloMo = false;
					PlayImmediateTone(600, 10);
				}
			}
		}
		if (!canSloMo) {
			if (!joy1Btn(12)) {
				canSloMo = true;
			}
		}
		if (canRevDir) {
			if (!revDir) {
				if (joy1Btn(11)) {
					revDir = true;
					canRevDir = false;
					PlayImmediateTone(300, 10);
				}
			} else {
				if (joy1Btn(11)) {
					revDir = false;
					canRevDir = false;
					PlayImmediateTone(800, 10);
				}
			}
		}
		if (!canRevDir) {
			if (!joy1Btn(11)) {
				canRevDir = true;
			}
		}

		// -------------------------------	End Drive Code	-------------------------------
		if (joystick.joy2_TopHat == 0) {
			motor[motorLift] = 100;
			motor[motorLift2] = 100;
			motor[motorLift3] = 100;
		} else if (joystick.joy2_TopHat == 4) {
			motor[motorLift] = -100;
			motor[motorLift2] = -100;
			motor[motorLift3] = -100;
		} else {
			motor[motorLift] = 0;
			motor[motorLift2] = 0;
			motor[motorLift3] = 0;
		}

		if (joy2Btn(1) || joy1Btn(1))
			motor[motorBelt] = 100;
		else if (joy2Btn(4) || joy1Btn(4))
			motor[motorBelt] = -100;
		else
			motor[motorBelt] = 0;


		// if (joy2Btn(8)) {
			// servo[srvoF1] = srvoVal[0][0];
		// }
		// if (joy2Btn(6)) {
			// servo[srvoF1] = srvoVal[0][1];
		// }
		if (joy2Btn(5)) {
			servo[servoStop] = srvoVal[1][0];
		}
		if (joy2Btn(7)) {
			servo[servoStop] = srvoVal[1][1];
		}

		if (canLower) {
		  if (!lowered) { //if not lowered
		    if (joy1Btn(8) || joy2Btn(8)) {
		      motor[motorLock] = -50;
		      wait1Msec(200);
		      motor[motorLock] = 0;
		      lowered = true;
		      canLower = false;
		    }
		  } else { //if lowered
		    if (joy1Btn(8) || joy2Btn(8)) {
		      motor[motorLock] = 50;
		      wait1Msec(200);
		      motor[motorLock] = 0;
		      lowered = false;
		      canLower = false;
		    }
		  }
		} else {
		  if (!joy1Btn(8) && !joy2Btn(8)) {
		    canLower = true;
		  }
		}
		if (joy2Btn(2)) {
		  servo[servoSweep] = 122;
		} else if (joy2Btn(3)) {
		  servo[servoSweep] = 105;
		 }

	} //while true
} //task main
