#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  none)
#pragma config(Motor,  motorA,          ,              tmotorNormal, openLoop, encoder)
#pragma config(Motor,  motorB,          ,              tmotorNormal, openLoop)
#pragma config(Motor,  motorC,          ,              tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     motorBackLeft,    tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorBackRight,    tmotorNormal, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     motorFrontLeft,   tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorFrontRight,   tmotorNormal, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_1,     motorLock,     tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motorD,        tmotorNormal, openLoop)

//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main(){

motor[motorFrontRight] =
motor[motorFrontLeft] =
motor[motorBackRight] =
motor[motorBackLeft] =


}
