#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop, encoder)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     motorLeft,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     motorRight,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motorBelt,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorUnused,   tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     motorLift,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motorLift2,    tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C4_1,    srvoGrab,             tServoStandard)
#pragma config(Servo,  srvo_S1_C4_2,    srvoDropper,          tServoStandard)
#pragma config(Servo,  srvo_S1_C4_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//####################################################################################//
//																																										//
//                              2014-2015 Motor Control Code													//
//                         Teams 3983 and 7005 - Highlands Robotics										//
//                                    Code by Ali Malik 															//
//																																										//
//####################################################################################//


task main()
{

motor[motorLeft]= 50;
motor[motorRight]=50;
wait1Msec(1000); //off the ramp
motor[motorLeft]=0;
motor[motorRight]=0;

servo[srvoGrab] = 157; //clamps the thing


motor[motorLift]= 30;
motor[motorLift2]= 30;
wait1Msec(1000); //lifts the bucket
motor[motorLeft]=0;
motor[motorRight]=0;

servo[srvoDropper]= 126; // RELEASE THE Kraken(bucket servo)


motor[motorLift]= -30;
motor[motorLift2]= -30;
wait1Msec(1000); // bring bucket down
motor[motorLeft]=0;
motor[motorRight]=0;

motor[motorLeft]= -50;
motor[motorRight]= -50;
wait1Msec(1000); //goes backwards
motor[motorLeft]=0;
motor[motorRight]=0;

motor[motorLeft]= 45;
motor[motorRight]= 0; // turns
wait1Msec(1000);

motor[motorLeft]= 50;
motor[motorRight]= 50; // move fwrd
wait1Msec(1000);

motor[motorLeft]= 45;
motor[motorRight]= 0; //turn again
wait1Msec(1000);

motor[motorLeft]= -50;
motor[motorRight]= -50; // goes backword, brings pole in goal
wait1Msec(1000);

}
