#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     Sonar,          sensorSONAR)
#pragma config(Sensor, S3,     Ir,             sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  mtr_S1_C1_1,     motorLeft,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorRight,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motorBelt,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorLift,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     motorSweeper,  tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     Chain,         tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C4_1,    servoClamp,           tServoStandard)
#pragma config(Servo,  srvo_S1_C4_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//#include "joystickdriver.c"
#include "../Globalfunctions/globalfunctions.c"
#include "../../2013-FTC/Music/James_Music.c"
void stopAllMotors();

task main()
{

moveForward(4000, 100);
	//motor[motorRight]=100;
	//motor[motorLeft]=100;
	//wait1Msec(4000);

	while(true){
		if(SensorValue(Sonar) <=10){
			stopAllMotors();
			//raise the box with the ball in it
			motor[Chain]=100;
			if (SensorValue(Sonar) <50) {
				motor[Chain]=20;
				wait1Msec(1000);
				}	else{
				//tilt mehanic? servo?
			}
			//put it up there^
			servo[servoClamp] = 90;
			motor[motorRight]=-100;
			motor[motorLeft]=-100;
			wait1Msec(5000);
			}	else {
			motor[motorRight]=100;
			motor[motorLeft]=100;
			wait1Msec(1000);
		}
		/*	(SensorValue(Sonar) <=10)
		servo[servoClamp] =90;
		motor[motorRight]=-100;
		motor[motorLeft]=-100
		wait1Msec(6000) */
	}
}

void stopAllMotors() {
	motor[0]=0;
	motor[1]=0;
	motor[2]=0;
	motor[3]=0;
	motor[4]=0;
	motor[5]=0;
	motor[6]=0;
	motor[7]=0;
}
