#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  HTMotor)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop, encoder)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     motorLeft,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     motorRight,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motorSpinner,  tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorLauncher, tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     motorH,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     motorI,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    servoLeft,            tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    servoRight,           tServoStandard)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//####################################################################################//
//																																										//
//                                 2014-2015 Autonomous Code													//
//                         Teams 3983 and 7005 - Highlands Robotics										//
//                                    Code by T. Kluge																//
//																																										//
//####################################################################################//

// User Config ---------------
bool inDebug = true;
// End Config ----------------
#include "../drivers/JoystickDriver_CustomNoSplash.c"
#include "MenuSelector.c"
#include "../GlobalFunctions/debug.h"
#include "../GlobalFunctions/GlobalFunctions.c"

//variable initialization

bool AUTON_1_NAME = false;
bool AUTON_2_NAME = false;

//Main Program

task main() {
	//dummy autonomous

	moveForward(3000, 100);
	turnLeft(2000, 100);
	moveForward(2000, 100);
	turnRight(1000, 100);

	chooseProgram(); //start the program chooser

	switch (PROGID) { //handle the results from the program chooser
		case 1:
			AUTON_1_NAME = true;
			debug("Auton prog set to AUTON_1_NAME");
			break;
		case 2:
			AUTON_2_NAME = true;
			debug("Auton prog set to AUTON_2_NAME");
			break;
		default:
			AUTON_1_NAME = true;
			debug("Auton prog defaulted to AUTON_1_NAME");
			PlaySoundFile("Woops.rso");
			break;
	}

	while (true) { //do the thing
		break;
	}
}
