#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  none)
#pragma config(Motor,  motorA,          ,              tmotorNormal, openLoop, encoder)
#pragma config(Motor,  motorB,          ,              tmotorNormal, openLoop)
#pragma config(Motor,  motorC,          ,              tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     motorBack1,    tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorBack2,    tmotorNormal, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     motorFront1,   tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorFront2,   tmotorNormal, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_1,     motorLock,     tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motorD,        tmotorNormal, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//####################################################################################//
//																																										//
//                              2014-2015 3983 Autonomous Code												//
//                         Teams 3983 and 7005 - Highlands Robotics										//
//                                    Code by T. Kluge																//
//																																										//
//####################################################################################//

// User Config ---------------
bool inDebug = true;
// End Config ----------------

#include "JoystickDriver.c"
//#include "../GlobalFunctions/debug.h"

int srvoVal[] = {103,194};
int ff[] = {490, 613, 640, 750, 640, 750};

task main() {
	nVolume = 3;
	PlayImmediateTone(400, 20);
	waitForStart();
	ClearSounds();
			PlayImmediateTone(ff[0], 10);
			// PlayImmediateTone(ff[1], 10);
			// PlayImmediateTone(ff[2], 10);
			// PlayImmediateTone(ff[3], 20);
			// PlayImmediateTone(ff[4], 10);
			// PlayImmediateTone(ff[5], 40);

			motor[motorBack1] = 100;
			motor[motorBack2] = 100;
			motor[motorFront1] = 100;
			motor[motorFront2] = 100;
			wait1Msec(3000);
			motor[motorBack1] = 0;
			motor[motorBack2] = 0;
			motor[motorFront1] = 0;
			motor[motorFront2] = 0;
}
