#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  HTMotor)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     HTIRS2L,        sensorI2CCustom)
#pragma config(Sensor, S3,     HTSMUX,         sensorI2CCustom)
#pragma config(Sensor, S4,     US1,            sensorSONAR)
#pragma config(Motor,  motorA,          motorAutoScore, tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     motorLeft,     tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     motorRight,    tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     motorArm,      tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C4_1,     motorH,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     motorWinch,    tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    servoSweep,           tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    servo5,               tServoStandard)
#pragma config(Servo,  srvo_S1_C3_3,    servoLift,            tServoStandard)
#pragma config(Servo,  srvo_S1_C3_4,    servo2,               tServoStandard)
#pragma config(Servo,  srvo_S1_C3_5,    servoUSSeeker,        tServoStandard)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//###################################################################################//
//
//								2013-2014 Menu Test Code
//							 Team 3983 - Highlands Robotics
//						        Code by T. Kluge
//
//###################################################################################//

#include "MenusAndIcons.c";

string menuFirst = "Choose Program to Run:";
string progFirst = "fw-fw-L1";
string progSecond = "fw-fw-L2";
string progThird = "fw-bw-L1";
string progFourth = "fw-bw-L2";

int totalChoices = 4;
int selectionValue = 1;
int selectedProgram = -1;

bool progSelected = false;

void updateDisplay();
void updateSelFirst();
void updateSelSecond();
void updateSelThird();
void updateSelFourth();
void runSelectedPgm();

task main() {

	//Initialize the display with the program choices
	updateSelFirst();

	wait1Msec(50);

	while (!progSelected) {
		//Right arrow

		if (nNxtButtonPressed == 1) {
			PlaySoundFile("! Click.rso");
			eraseDisplay();
			selectionValue++;
			updateDisplay();
			wait1Msec(300);
		}

		//Left arrow
		if (nNxtButtonPressed == 2) {
			PlaySoundFile("! Click.rso");
			eraseDisplay();
			selectionValue--;
			updateDisplay();
			wait1Msec(300);
		}

		//Center orange button
		if (nNxtButtonPressed == 3) {
			PlaySoundFile("! Attention.rso");
			progSelected = true;
			selectedProgram = selectionValue;
			runSelectedPgm();
		}

		if (selectionValue == 5) {
			selectionValue = 1;
			eraseDisplay();
			updateDisplay();
		}
		if (selectionValue == 0) {
			selectionValue = 4;
			eraseDisplay();
			updateDisplay();
		}
	}
}

void updateDisplay() {
	if (selectionValue == 1) {
		updateSelFirst();
	}
	if (selectionValue == 2) {
		updateSelSecond();
	}
	if (selectionValue == 3) {
		updateSelThird();
	}
	if (selectionValue == 4) {
		updateSelFourth();
	}
}

void updateSelFirst() {

	nxtDisplayTextLine (2, "%s <", progFirst);
	nxtDisplayTextLine (3, "%s", progSecond);
	nxtDisplayTextLine (4, "%s", progThird);
	nxtDisplayTextLine (5, "%s", progFourth);

}

void updateSelSecond() {

	nxtDisplayTextLine (2, "%s", progFirst);
	nxtDisplayTextLine (3, "%s <", progSecond);
	nxtDisplayTextLine (4, "%s", progThird);
	nxtDisplayTextLine (5, "%s", progFourth);

}
void updateSelThird() {

	nxtDisplayTextLine (2, "%s", progFirst);
	nxtDisplayTextLine (3, "%s", progSecond);
	nxtDisplayTextLine (4, "%s <", progThird);
	nxtDisplayTextLine (5, "%s", progFourth);

}
void updateSelFourth() {

	nxtDisplayTextLine (2, "%s", progFirst);
	nxtDisplayTextLine (3, "%s", progSecond);
	nxtDisplayTextLine (4, "%s", progThird);
	nxtDisplayTextLine (5, "%s <", progFourth);

}

void runSelectedPgm() {
	//set all control variables in this function to tell the robot what to do in autonomous.
	//This just makes it a bit easier so that we dont have to use numbers to refer to the code conditions

	if (selectedProgram == 1) {
		bool fw_s_fw_L1 = true;
		bool fw_s_fw_L2 = false;
		bool fw_s_bw_L1 = false;
		bool fw_s_bw_L2 = false;
	}

	if (selectedProgram == 2) {
		bool fw_s_fw_L1 = false;
		bool fw_s_fw_L2 = true;
		bool fw_s_bw_L1 = false;
		bool fw_s_bw_L2 = false;
	}

	if (selectedProgram == 3) {
		bool fw_s_fw_L1 = false;
		bool fw_s_fw_L2 = false;
		bool fw_s_bw_L1 = true;
		bool fw_s_bw_L2 = false;
	}

	if (selectedProgram == 4) {
		bool fw_s_fw_L1 = false;
		bool fw_s_fw_L2 = false;
		bool fw_s_bw_L1 = false;
		bool fw_s_bw_L2 = true;
	}
}
